### ISSUE TITLE
file descriptor not closed after socket compat http request 

### ISSUE THREAD

**Issue by leafo** [daurnimator/lua-http#55]
```lua
local cqueues = require("cqueues")
local cq = cqueues.new()

local http = require("http.compat.socket")

cq:wrap(function()
  while true do
    assert(http.request("http://leafo.net"))
  end
end)

assert(cq:loop())
```

Run this code while monitoring open file descriptors.

Garbage collection does not happen fast enough to clean up all the resources created, so eventually you'll hit your system file descriptor limit and the program will crash. Callling `collectgarbage()` in the loop fixes the problem, but it should not be necessary.

**Comment by daurnimator** [comment]
This issue isn't limited to the 'compat' interface.

```lua
local http_request = require "http.request"
while true do
	local h, s = http_request.new_from_uri("http://leafo.net"):go()
	if h then
		s:shutdown()
	end
end
```

**Comment by leafo** [comment]
In my very limited testing, I noticed that the FD count would occasionally decrease, but it wouldn't collect all of them. The total open would increase faster than those sporadic collections would free the files. Maybe because it's not aware of FD, which is much more limited resource than memory, it lets it sit around for additional generations. I think in general it makes most sense to close external resources manually when you're done with them instead of waiting for GC to collect them.

**Comment by daurnimator** [comment]
> In my very limited testing, I noticed that the FD count would occasionally decrease, but it wouldn't collect all of them. The total open would increase faster than those sporadic collections would free the files.

Yeah it looks like the GC isn't getting run enough: the GC only does a full collection when memory usage doubles. The current release of lpeg_patterns uses 24MB of memory on patterns alone (this is fixed in git HEAD), which means that the GC won't do a full pass until 48MB is used! (which is far more memory than gets used by *thousands* of http requests).
If I leave it long enough (or increase my file descriptor limit) I see the GC eventually doing it's job.

> Maybe because it's not aware of FD, which is much more limited resource than memory, it lets it sit around for additional generations

Correct, the GC has no concept of a limited resource except memory.

Perhaps I should force a full GC on EMFILE and retry? I already do in http.server: perhaps the client code needs the same treatment?

> I think in general it makes most sense to close external resources manually when you're done with them instead of waiting for GC to collect them.

I agree. and I usually do.
However shutting down a stream doesn't currently close the underlying connection: I imagined in certain cases you'd want to do things with the connection object even when there are no 'live' streams (particularly in the HTTP2 server-side case).
This was also leaving my options open for client side connection pooling.

I'm trying to figure out the best way forward here....
